<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class BlogCategory extends Model
{
    protected $table = 'blog_categories';
    protected $fillable = ['name', 'lang', 'status', 'image', 'type', 'parent', 'slug'];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::creating(function ($model) {
            $model->slug = Str::slug($model->name, '-');
        });
        self::updating(function ($model) {
            $model->slug = Str::slug($model->name, '-');
        });
    }

    public function parent()
    {
        return $this->hasOne(BlogCategory::class, 'parent');
    }

    public function children()
    {
        return $this->hasMany(BlogCategory::class, 'parent', 'id');
    }

    public function blogs()
    {
        return $this->hasMany(Blog::class,  'blog_categories_id', 'id');
    }
}
