# not modify
name: deployment

on:
  push:
    branches:
      - main
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: main
    timeout-minutes: 30

    defaults:
      run:
        shell: bash
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Executing remote command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          PASSWORD: ${{ secrets.PWD }}
          script: |
            cd /home/wlinvn/domains/wlin.vn/public_html
            git pull
            cd @core
            (php artisan down) || true
            composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader
            php artisan optimize
            php artisan migrate --force
            php artisan up
            echo "Setup done"

